### PR TITLE
Create mfpurrs.json

### PR DESCRIPTION
**Pull request by M4cs**
https://mfpurrs.com

### CODE REVIEW

**Review by zss798 — COMMENTED** [review]
35

**Comment by M4cs** [comment]
What does 35 mean?

**Comment by zss798** [comment]
> 
Because I sent it out inadvertently

**Comment by M4cs** [comment]
I updated the JSON to include the collection trait_type

**Comment by zss798** [comment]
> 

I came in to see the cat's various attributes, but I found that I couldn't find it

**Comment by M4cs** [comment]
It might be because it's too big, I can provide the data here:

"trait_type:value:" : amount
```
{
    "background:blue": 1497,
    "background:green": 1471,
    "background:matrix": 321,
    "background:orange": 1540,
    "background:purple": 1488,
    "background:red": 1419,
    "background:space": 213,
    "background:this is fine": 334,
    "background:windows": 251,
    "background:yellow": 1466,
    "clothing:black hoodie": 446,
    "clothing:blue tee": 395,
    "clothing:blue tracksuit": 389,
    "clothing:bomber": 387,
    "clothing:fashion hoodie": 468,
    "clothing:gold chain": 115,
    "clothing:hacker": 386,
    "clothing:hawaiian shirt": 416,
    "clothing:none": 2526,
    "clothing:office shirt": 411,
    "clothing:red tee": 404,
    "clothing:red tracksuit": 402,
    "clothing:robe": 402,
    "clothing:silver chain": 131,
    "clothing:space suit": 412,
    "clothing:tie dye tee": 431,
    "eye color:bloodshot": 209,
    "eye color:blue": 1980,
    "eye color:green": 1894,
    "eye color:orange": 1985,
    "eye color:purple": 2001,
    "eye color:yellow": 1931,
    "eyewear:aviators": 608,
    "eyewear:bitcoin maxi": 280,
    "eyewear:blue noggles": 506,
    "eyewear:deal with it": 636,
    "eyewear:morpheus": 344,
    "eyewear:nerd": 612,
    "eyewear:none": 4961,
    "eyewear:red noggles": 499,
    "eyewear:tired": 600,
    "eyewear:viper shades": 586,
    "eyewear:vr headset": 144,
    "fur:black": 96,
    "fur:cheshire": 420,
    "fur:cool blue": 2350,
    "fur:cream": 2381,
    "fur:gold": 9,
    "fur:orange tabby": 2268,
    "fur:siamese": 2380,
    "fur:white": 96,
    "hat:420 bucket hat": 418,
    "hat:black beanie": 408,
    "hat:black headphones": 127,
    "hat:cowboy hat": 538,
    "hat:durag": 404,
    "hat:fedora": 436,
    "hat:fitted cap": 407,
    "hat:golden headphones": 100,
    "hat:golf": 438,
    "hat:keffiyeh": 418,
    "hat:none": 440,
    "hat:orange beanie": 437,
    "hat:rainbow": 469,
    "hat:red bucket hat": 421,
    "hat:safari": 422,
    "hat:snapback": 371,
    "hat:sports headband": 427,
    "hat:wizard hat": 430,
    "mouth:bored": 2233,
    "mouth:bubble gum": 1450,
    "mouth:cig": 1113,
    "mouth:mustache": 584,
    "mouth:smile": 2728,
    "mouth:vape": 995,
    "mouth:yawn": 897,
    "piercing:earring": 338,
    "piercing:none": 6888
}
```

**Comment by M4cs** [comment]
Any update?

**Pull request merged**
