### PR TITLE
Create PNG Suite.json

### PR DESCRIPTION
**Pull request by Posvar**
Collection launched 6/28 and "scribed" out within an hour: see: ethscri.be/pngsuite

### CODE REVIEW

**Comment by genecyber** [comment]
2 things, 
1: tests fail on your json file: Error parsing file ./projects/PNG Suite.json: Unexpected token ] in JSON at position 51788
2: try to avoid spaces in file names (rename PNG Suite.json > PNG-Suite.json)

**Comment by Posvar** [comment]
I renamed PNG Suite.json to PNG-Suite.json (removed space) and re-committed. Is that enough?

**Comment by genecyber** [comment]
remove the comma here: https://github.com/EmblemCompany/EthscriptionMetadata/blob/96505b8b6a1df6970166e0f2c028422e7691ded4/projects/PNG-Suite.json#L2053

**Comment by Posvar** [comment]
updated to remove the comma in line 2053 as requested.

**Pull request closed without merging**
